spring:
    profiles:
        active:
        - dev
---
server:
    port: 8301
spring:
    profiles: dev
    application:
        name: microservicecloud-config-client2
eureka:
    client:
        service-url:
            defaultZone: http://192.168.79.1:7001/eureka/
            
       

---
server:
    port: 8302
spring:
    profiles: test
    application:
        name: microservicecloud-config-client2
eureka:
    client:
        service-url:
            defaultZone: http://192.168.79.1:7001/eureka/