spring:
    profiles:
        active:
        - dev
---
server:
    port: 7001
spring:
    profiles: dev
    application:
        name: microservicecloud-config-eureka-client
eureka:
    client:
        service-url:
            defaultZone: http://192.168.79.1:7001/eureka/
        register-with-eureka: false
        fetch-registry: false
       

---
server:
    port: 7001
spring:
    profiles: test
    application:
        name: microservicecloud-config-eureka-client
eureka:
    client:
        service-url:
            defaultZone: http://192.168.79.1:7001/eureka/
        register-with-eureka: false
        fetch-registry: false